name: "Build ferris/sweep"
on:
    workflow_dispatch:
    push:
        branches:
            - miryoku

jobs:
    build:
        uses: ./.github/workflows/main.yml
        with:
            keyboard: '["ferris/sweep"]'
            # alphas: '["qwerty"]'
            nav: '["vi"]'
            clipboard: '["Win"]'
